In [11]:
import csv
import numpy
import sklearn
import nltk
import numpy as np
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem.porter import PorterStemmer
# from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score 
from sklearn.metrics import average_precision_score
from sklearn.metrics import f1_score
import sklearn
from sklearn.metrics import precision_recall_fscore_support
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [12]:
datafile = open('IMDB_Movie_Reviews.csv', 'r', encoding="utf8")
myreader = csv.reader(datafile)
stop_words = set(stopwords.words('english'))

In [13]:
dicts = []
corpus = []
labels = []
for line in myreader:
    tokens = nltk.word_tokenize(line[0])
    filtered_sentence = [w for w in tokens if not w.lower() in stop_words]
    filtered_sentence = []

    for w in tokens:
        if w not in stop_words:
            filtered_sentence.append(w)

    words = [word for word in filtered_sentence if word.isalpha()]

    porter = PorterStemmer()
    stemmed = [porter.stem(word) for word in words]

    dict = {
        "Review": stemmed,
        "Label": line[1],
    }
    dicts.append(dict)

    string_tokens=' '.join([str(elem) for elem in stemmed])
    corpus.append(string_tokens)
    labels.append(line[1])

In [15]:
x_train, x_test, y_train, y_test = train_test_split(corpus, labels, test_size = 0.20, train_size = 0.80, random_state=42)

In [25]:
tfidf = TfidfVectorizer(max_features = 1000000, ngram_range = (1, 3), stop_words = 'english')
tfidf.fit(corpus)
tfidf_train = tfidf.transform(x_train)
tfidf_test = tfidf.transform(x_test)

In [28]:
NaiveBayesTFIDF = MultinomialNB(alpha = 1)
NaiveBayesTFIDF.fit(tfidf_train,y_train)
y_pred = NaiveBayesTFIDF.predict(tfidf_test)

accuracy_score_NaiveBayes = accuracy_score(y_test ,y_pred)
print("Accuracy Score of Naive Bayes with My Feature Extension is: ", round(accuracy_score_NaiveBayes, 8))

prf_NBTFIDF = precision_recall_fscore_support(y_test ,y_pred, average = 'weighted')
print("Precision Score of Naive Bayes with My Feature Extension is: ", round(prf_NBTFIDF[0], 8))
print("Recall Score of Naive Bayes with My Feature Extension is: ", round(prf_NBTFIDF[1], 8))
print("F1 Score of Naive Bayes with My Feature Extension is: ", round(prf_NBTFIDF[2], 8), "\n")

print("Confusion Matrix of Naive Bayes My Feature Extension: ")
print(confusion_matrix(y_test ,y_pred))

Accuracy Score of Naive Bayes with My Feature Extension is:  0.8830234
Precision Score of Naive Bayes with My Feature Extension is:  0.88324859
Recall Score of Naive Bayes with My Feature Extension is:  0.8830234
F1 Score of Naive Bayes with My Feature Extension is:  0.88302126 

Confusion Matrix of Naive Bayes My Feature Extension: 
[[2204  321]
 [ 264 2212]]


In [29]:
LSVMTFIDF = LinearSVC(C = 1)
LSVMTFIDF.fit(tfidf_train, y_train)
LSVM_y_pred = LSVMTFIDF.predict(tfidf_test)

accuracy_score_SVM = accuracy_score(y_test ,LSVM_y_pred)
print("Accuracy Score of SVM with My Feature Extension is: ", round(accuracy_score_SVM, 8))

prf_SVMTFIDF = precision_recall_fscore_support(y_test ,LSVM_y_pred, average='macro')
print("Precision Score of SVM with My Feature Extension is: ", round(prf_SVMTFIDF[0], 8))
print("Recall Score of SVM with My Feature Extension is: ", round(prf_SVMTFIDF[1], 8))
print("F1 Score of SVM with My Feature Extension is: ", round(prf_SVMTFIDF[2], 8), "\n")

print("Confusion Matrix of SVM with My Feature Extension: ")
print(confusion_matrix(y_test ,LSVM_y_pred))

Accuracy Score of SVM with My Feature Extension is:  0.89542092
Precision Score of SVM with My Feature Extension is:  0.89564884
Recall Score of SVM with My Feature Extension is:  0.89554999
F1 Score of SVM with My Feature Extension is:  0.89541889 

Confusion Matrix of SVM with My Feature Extension: 
[[2228  297]
 [ 226 2250]]


In [30]:
from sklearn.linear_model import LogisticRegression

LogisticRTFIDF = LogisticRegression(penalty = 'l2', solver = 'newton-cg')
LogisticRTFIDF.fit(tfidf_train, y_train)
LogisticR_y_pred = LogisticRTFIDF.predict(tfidf_test)

accuracy_score_LR = accuracy_score(y_test, LogisticR_y_pred)
print("Accuracy Score of Logistic Regression with My Feature Extension is: ", round(accuracy_score_LR, 8))

prf_LRTFIDF = precision_recall_fscore_support(y_test, LogisticR_y_pred, average='macro')
print("Precision Score of Logistic Regression with My Feature Extension is: ", round(prf_LRTFIDF[0], 8))
print("Recall Score of Logistic Regression with My Feature Extension is: ", round(prf_LRTFIDF[1], 8))
print("F1 Score of Logistic Regression with My Feature Extension is: ", round(prf_LRTFIDF[2], 8), "\n")

print("Confusion Matrix of Logistic Regression with My Feature Extension: ")
print(confusion_matrix(y_test, LogisticR_y_pred))


Accuracy Score of Logistic Regression with My Feature Extension is:  0.8860228
Precision Score of Logistic Regression with My Feature Extension is:  0.88669355
Recall Score of Logistic Regression with My Feature Extension is:  0.88623522
F1 Score of Logistic Regression with My Feature Extension is:  0.88600354 

Confusion Matrix of Logistic Regression with My Feature Extension: 
[[2183  342]
 [ 228 2248]]
