In [132]:
# import nltk
import csv
import numpy
import sklearn
import nltk
import numpy as np
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem.porter import PorterStemmer
# from sklearn.feature_extraction.text import CountVectorizer
# from sklearn.model_selection import train_test_split
# from sklearn.naive_bayes import MultinomialNB
# from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
# from sklearn.svm import LinearSVC
# from sklearn.metrics import confusion_matrix,classification_report,accuracy_scorefrom sklearn.metrics 
# from sklearn.metrics import average_precision_score
# from sklearn.metrics import f1_score
import sklearn
from sklearn.metrics import precision_recall_fscore_support


In [133]:
datafile = open('IMDB_Movie_Reviews.csv', 'r', encoding="utf8")
myreader = csv.reader(datafile)
stop_words = set(stopwords.words('english'))

In [134]:
dicts = []
corpus = []
labels = []
for line in myreader:
    tokens = nltk.word_tokenize(line[0])
    filtered_sentence = [w for w in tokens if not w.lower() in stop_words]
    filtered_sentence = []

    for w in tokens:
        if w not in stop_words:
            filtered_sentence.append(w)

    words = [word for word in filtered_sentence if word.isalpha()]

    porter = PorterStemmer()
    stemmed = [porter.stem(word) for word in words]

    dict = {
        "Review": stemmed,
        "Label": line[1],
    }
    dicts.append(dict)

    string_tokens=' '.join([str(elem) for elem in stemmed])
    corpus.append(string_tokens)
    labels.append(line[1])

In [135]:
print(corpus[10])
print(labels[10])

i actual felt bad actor thing no doubt high school drama class could better job least well job the actor must thought would big chanc work film certainli besid terribl act stori bore part predict the one remot control even make sens to bad caus best premis br br i support low budget film give new film maker fair chanc turkey wast time insult viewer i watch good comment post they must plant peopl tie film you may fool peopl watch ca fool like br br i gave instead least boxer stori tri heart warm sure fail miser tri i reserv worst br br do favor skip dribbl i wish i
0


In [136]:
x_train, x_test, y_train, y_test = train_test_split(corpus, labels, test_size = 0.20, train_size = 0.80, random_state=42)
vec = CountVectorizer(stop_words='english')
x_train = vec.fit_transform(x_train).toarray()
x_test = vec.transform(x_test).toarray()

In [142]:
NaiveBayes = MultinomialNB(alpha = 1)
NaiveBayes.fit(x_train,y_train)
y_pred = NaiveBayes.predict(x_test)

accuracy_score_NaiveBayes = accuracy_score(y_test ,y_pred)
print("Accuracy Score of Naive Bayes is: ", round(accuracy_score_NaiveBayes, 6))

prf_NB = precision_recall_fscore_support(y_test ,y_pred, average='weighted')
print("Precision Score of Naive Bayes is: ", round(prf_NB[0], 6))
print("Recall Score of Naive Bayes is: ", round(prf_NB[1], 6))
print("F1 Score of Naive Bayes is: ", round(prf_NB[2], 6), "\n")

print("Confusion Matrix of Naive Bayes: ")
print(confusion_matrix(y_test ,y_pred))

Accuracy Score of Naive Bayes is:  0.853829
Precision Score of Naive Bayes is:  0.854514
Recall Score of Naive Bayes is:  0.853829
F1 Score of Naive Bayes is:  0.853719 

Confusion Matrix of Naive Bayes: 
[[2217  308]
 [ 423 2053]]


In [144]:
LSVM = LinearSVC(C = 1)
LSVM.fit(x_train, y_train)
LSVM_y_pred = LSVM.predict(x_test)

accuracy_score_SVM = accuracy_score(y_test ,LSVM_y_pred)
print("Accuracy Score of SVM is: ", round(accuracy_score_SVM, 6))

prf_SVM = precision_recall_fscore_support(y_test ,LSVM_y_pred, average='macro')
print("Precision Score of SVM is: ", round(prf_SVM[0], 6))
print("Recall Score of SVM is: ", round(prf_SVM[1], 6))
print("F1 Score of SVM is: ", round(prf_SVM[2], 6), "\n")

print("Confusion Matrix of SVM: ")
print(confusion_matrix(y_test ,LSVM_y_pred))

C:\Users\Arya\anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


Accuracy Score of SVM is:  0.85003
Precision Score of SVM is:  0.850033
Recall Score of SVM is:  0.849992
F1 Score of SVM is:  0.850008 

Confusion Matrix of SVM: 
[[2156  369]
 [ 381 2095]]


In [140]:
LogisticR = LogisticRegression(penalty='l2',solver='newton-cg')
LogisticR.fit(x_train, y_train)
LogisticR_y_pred = LogisticR.predict(x_test)

accuracy_score_LR = accuracy_score(y_test, LogisticR_y_pred)
print("Accuracy Score of Logistic Regression is: ", round(accuracy_score_LR, 6))

prf_LR = precision_recall_fscore_support(y_test, LogisticR_y_pred, average='macro')
print("Precision Score of Logistic Regression is: ", round(prf_LR[0], 6))
print("Recall Score of Logistic Regression is: ", round(prf_LR[1], 6))
print("F1 Score of Logistic Regression is: ", round(prf_LR[2], 6), "\n")

print("Confusion Matrix of Logistic Regression: ")
print(confusion_matrix(y_test, LogisticR_y_pred))


Accuracy Score of Logistic Regression is:  0.87
Precision Score of Logistic Regression is:  0.8698113258848488
Recall Score of Logistic Regression is:  0.87
F1 Score of Logistic Regression is:  0.87 

Confusion Matrix of Logistic Regression: 
[[2193  332]
 [ 319 2157]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=10000,ngram_range=(1,3), stop_words='english')
tfidf.fit(corpus)
tfidf_train=tfidf.transform(x_train)
tfidf_test= tfidf.transform(x_test)

In [42]:
#Naive Bayes with Tf-idf Vectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

nv1 = MultinomialNB(alpha=0.1)
nv1.fit(tfidf_train,y_train)
y_pred_nv1_tfidf= nv.predict(cv_test)
print(confusion_matrix(y_test,y_pred_nv1_tfidf))
print(classification_report(y_test,y_pred_nv1_tfidf))
print(accuracy_score(y_test,y_pred_nv1_tfidf))