In [1]:
# import nltk
import csv
import numpy
import sklearn
import nltk
import numpy as np
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem.porter import PorterStemmer
# from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.metrics import average_precision_score
from sklearn.metrics import f1_score
import sklearn
from sklearn.metrics import precision_recall_fscore_support
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score


In [4]:
datafile = open('IMDB_Movie_Reviews.csv', 'r', encoding="utf8")
myreader = csv.reader(datafile)
stop_words = set(stopwords.words('english'))

In [5]:
dicts = []
corpus = []
labels = []
for line in myreader:
    tokens = nltk.word_tokenize(line[0])
    filtered_sentence = [w for w in tokens if not w.lower() in stop_words]
    filtered_sentence = []

    for w in tokens:
        if w not in stop_words:
            filtered_sentence.append(w)

    words = [word for word in filtered_sentence if word.isalpha()]

    porter = PorterStemmer()
    stemmed = [porter.stem(word) for word in words]

    dict = {
        "Review": stemmed,
        "Label": line[1],
    }
    dicts.append(dict)

    string_tokens=' '.join([str(elem) for elem in stemmed])
    corpus.append(string_tokens)
    labels.append(line[1])

In [6]:
print(corpus[10])
print(labels[10])

i actual felt bad actor thing no doubt high school drama class could better job least well job the actor must thought would big chanc work film certainli besid terribl act stori bore part predict the one remot control even make sens to bad caus best premis br br i support low budget film give new film maker fair chanc turkey wast time insult viewer i watch good comment post they must plant peopl tie film you may fool peopl watch ca fool like br br i gave instead least boxer stori tri heart warm sure fail miser tri i reserv worst br br do favor skip dribbl i wish i
0


In [17]:
x_train, x_test, y_train, y_test = train_test_split(corpus, labels, test_size = 0.20, train_size = 0.80, random_state=42)

In [37]:
tfidf = TfidfVectorizer()
tfidf.fit(corpus)
tfidf_train = tfidf.transform(x_train)
tfidf_test = tfidf.transform(x_test)

In [44]:
NaiveBayesTFIDF = MultinomialNB(alpha = 1)
NaiveBayesTFIDF.fit(tfidf_train,y_train)
y_pred = NaiveBayesTFIDF.predict(tfidf_test)

accuracy_score_NaiveBayes = accuracy_score(y_test ,y_pred)
print("Accuracy Score of Naive Bayes with TF-IDF is: ", round(accuracy_score_NaiveBayes, 8))

prf_NBTFIDF = precision_recall_fscore_support(y_test ,y_pred, average = 'weighted')
print("Precision Score of Naive Bayes with TF-IDF is: ", round(prf_NBTFIDF[0], 8))
print("Recall Score of Naive Bayes with TF-IDF is: ", round(prf_NBTFIDF[1], 8))
print("F1 Score of Naive Bayes with TF-IDF is: ", round(prf_NBTFIDF[2], 8), "\n")

print("Confusion Matrix of Naive Bayes with TF-IDF: ")
print(confusion_matrix(y_test ,y_pred))

Accuracy Score of Naive Bayes with TF-IDF is:  0.86162767
Precision Score of Naive Bayes with TF-IDF is:  0.86174526
Recall Score of Naive Bayes with TF-IDF is:  0.86162767
F1 Score of Naive Bayes with TF-IDF is:  0.86160028 

Confusion Matrix of Naive Bayes with TF-IDF: 
[[2204  321]
 [ 371 2105]]


In [49]:
LSVMTFIDF = LinearSVC(C = 1)
LSVMTFIDF.fit(tfidf_train, y_train)
LSVM_y_pred = LSVMTFIDF.predict(tfidf_test)

accuracy_score_SVM = accuracy_score(y_test ,LSVM_y_pred)
print("Accuracy Score of SVM with TF-IDF is: ", round(accuracy_score_SVM, 8))

prf_SVMTFIDF = precision_recall_fscore_support(y_test ,LSVM_y_pred, average='macro')
print("Precision Score of SVM with TF-IDF is: ", round(prf_SVMTFIDF[0], 8))
print("Recall Score of SVM with TF-IDF is: ", round(prf_SVMTFIDF[1], 8))
print("F1 Score of SVM with TF-IDF is: ", round(prf_SVMTFIDF[2], 8), "\n")

print("Confusion Matrix of SVM with TF-IDF: ")
print(confusion_matrix(y_test ,LSVM_y_pred))

Accuracy Score of SVM with TF-IDF is:  0.88222356
Precision Score of SVM with TF-IDF is:  0.88222075
Recall Score of SVM with TF-IDF is:  0.88225731
F1 Score of SVM with TF-IDF is:  0.88222037 

Confusion Matrix of SVM with TF-IDF: 
[[2219  306]
 [ 283 2193]]


In [54]:
from sklearn.linear_model import LogisticRegression

LogisticRTFIDF = LogisticRegression(penalty = 'l2', solver = 'newton-cg')
LogisticRTFIDF.fit(tfidf_train, y_train)
LogisticR_y_pred = LogisticRTFIDF.predict(tfidf_test)

accuracy_score_LR = accuracy_score(y_test, LogisticR_y_pred)
print("Accuracy Score of Logistic Regression with TF-IDF is: ", round(accuracy_score_LR, 8))

prf_LRTFIDF = precision_recall_fscore_support(y_test, LogisticR_y_pred, average='macro')
print("Precision Score of Logistic Regression with TF-IDF is: ", round(prf_LRTFIDF[0], 8))
print("Recall Score of Logistic Regression with TF-IDF is: ", round(prf_LRTFIDF[1], 8))
print("F1 Score of Logistic Regression with TF-IDF is: ", round(prf_LRTFIDF[2], 8), "\n")

print("Confusion Matrix of Logistic Regression with TF-IDF: ")
print(confusion_matrix(y_test, LogisticR_y_pred))


Accuracy Score of Logistic Regression with TF-IDF is:  0.88582284
Precision Score of Logistic Regression with TF-IDF is:  0.8860631
Recall Score of Logistic Regression with TF-IDF is:  0.88595491
F1 Score of Logistic Regression with TF-IDF is:  0.88582021 

Confusion Matrix of Logistic Regression with TF-IDF: 
[[2203  322]
 [ 249 2227]]


ValueError: Expected 2D array, got 1D array instead:
array=['thi one best comedi ever the write parodi soap brilliant cast well look name cast understand great if kevin kline fan alway fantast perform robert downey jr perfect if laugh seen movi sens humor'
 'thi film amaz it inspir piec cinema the charact fulli develop truth director luci walker bring film i highli recommend one look special film show human human condit luci wlaker showcas landscap beauti thi film id true exampl man natur sometim man man the inner turmoil triumph tremend subject matter the subject tiebtan view blind sign demon interest thi film shed light particular cultur never showcas luci walker given erik weihenmay voic would normal heard thank luci true vison filmmak'
 'i understand want make movi edgi differ i understand previou review comment movi my point soon movi end first comment happen rich princess want movi star talent use daddi money make movi wrote direct pay obvious close movi realiz charact develop direct begin middl end voyeur part good edgi point i saw women go hous find pictur screw caretak come side cold night believ check nois run caretak lover movi end one educ ignor arss i realli want know point director vision develop dead lover whi background caretak what point night vision what point lipstick car whi dead caretak whi tell us escap mental tom what urn oh lamp suppos signifi whose hous territori whi whi would caretak feel like hous aspect never pursu william defo i rent movi known edgi charact write back tell i need learn i mom middl america love movi chri'
 ...
 'thi get bash star david hasselhoff well let bash compar garbag call horror come nowaday film bad it beauti lesli cum she super hot ca talk well there great scene supernatur rape she show nice bodi linda blair noth well hasselhoff'
 'thi one worst movi ever it bad i laugh whole movi the plot so cheesi especi end thi movi turn i mean and i swear i think use sock puppet eel and horribl kiss scene middl two main charact happen divorc how predict it so terribl mom sister i could finish did finish year later the second time watch finish time comment throughout br br summari onli watch movi basher make hilari comment watch sleepov laugh i mean huge laugh also watch mockeri the metaphor explain movi thi movi shallow field full chees sock puppet'
 'my year old love i love wife love so famili as violenc level not realli violent mostli slap stick varieti nobodi truli die gore blood tortur certainli appropri children much mani saturday morn br br thi movi realli take idea cg movi br br first beauti graphic textur wonder done true depth tri realist form artist whole the moss stone rust metal relief wood stone everyth add br br charact model unlik mani contemporari cg movi quirki cute within artist whole the face may look less malleabl movi charact i think good thing lend verac strang may sound easier suspend br br hair fur cloth par least like pixar just note open scene fight giant slug gwizdo front farmer detail cloth caus paus movi admir br br the set far beyond like car even space done mani time fantasi environ dragon hunter compar scene never end stori lord ring artist whole lot good idea thrown effortlessli magnific vista like scene monster ride doorway storag facil see immens trash tower made abound movi everyth grand yet never dwelt upon background whole way the interlud walk area fantast fall the chines wall island float sky the broccoli sky that truli i believ cg go make someth take breath away br br the sound good music vari epic thank without vocal pure origin br br anim quit good lend inspir cartoon especi good use stretch squeez sometim realist model realist br br character well done gentl uncertain giant gradual grow confid bask attent littl br br gwizdo wili manag redeem end zoé realli chang want cute child chang anyway i least love recent charact sinc sulley monster br br the intern strife group get iron extern pressur proper fantasi br br the stori mostli reminisc never end stori especi world brake apart the monster pretti standard fare except flock one it lack emot impact realli strong point movi much fun ride lack annoy music scene replay former one action first scene thi movi want watch fun excit br br the whole movi i mention whole vision seem follow rigor br br it seem set readi adventur i one would hope br br one side note french actor sound bit like jean reno first i happi though one favorit nice hear new br br i give max rate bit surpris mediocr low rate i tri address concern made two review lowest vote approach movi adventur european movi oppos hollywood differ'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.